---
title: "Comparison of RF implementations within VSURF"
author: "Robin Genuer"
date: "12 avril 2018"
output: 
  html_document: 
    number_sections: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(cache = FALSE)
```

```{r, echo=FALSE}
resFiles <- list.files("outputs/")
for (fileName in resFiles) {
  load(paste0("outputs/", fileName))
}
```


```{r, cache=FALSE}
library(VSURF)
```

# `toys` data

```{r, cache=FALSE}
data(toys)
```

## Sequential with `randomForest`

```{r, eval=FALSE}
toysRFseq <- VSURF(toys$x, toys$y)
summary(toysRFseq)
```

## Sequential with `ranger`

```{r, eval=FALSE}
toysRangerSeq <- VSURF(toys$x, toys$y, RFimplementation = "ranger")
summary(toysRangerSeq)
```
 
## Parallel with `randomForest`

```{r, cache=FALSE}
ncores <- 32
```

### Fork

```{r, eval=FALSE}
toysRFfork <- VSURF(toys$x, toys$y, parallel = TRUE, clusterType = "FORK",
                        ncores = ncores)
summary(toysRFfork)
```

## Parallel with `ranger`

### Socket

```{r, eval=FALSE}
toysRangerPara <- VSURF(toys$x, toys$y, RFimplementation = "ranger",
                        parallel = TRUE, ncores = ncores)
summary(toysRangerPara)
```

### Fork

```{r, eval=FALSE}
toysRangerFork <- VSURF(toys$x, toys$y, RFimplementation = "ranger",
                        parallel = TRUE, clusterType = "FORK", ncores = ncores)
summary(toysRangerFork)
```

### Internal

```{r, eval=FALSE}
toysRangerParaInter <- VSURF(toys$x, toys$y, RFimplementation = "ranger",
                        parallel = TRUE, clusterType = "ranger",
                        ncores = ncores)
summary(toysRangerParaInter)
```


# `spam` data

```{r, cache=FALSE}
data("spam", package = "kernlab")
set.seed(9146301)
levels(spam$type) <- c("ok", "spam")
yTable <- table(spam$type)
indApp <- c(sample(1:yTable[2], yTable[2]/2),
            sample((yTable[2] + 1):nrow(spam), yTable[1]/2))
spamApp <- spam[indApp, ]
spamTest <- spam[-indApp, ]
```

```{r}
ncores <- 32
```


## Threshold step

```{r, eval=FALSE}
spamThres <- VSURF_thres(type~., spamApp, parallel = TRUE, ncores = ncores, clusterType="FORK")
save(spamThres, file = "outputs/spamThres.Rdata")
```

```{r}
spamThres$comput.time
```

```{r, eval=FALSE}
spamRgThres <- VSURF_thres(type~., spamApp, parallel = TRUE, ncores = ncores, clusterType="FORK", RFimplem = "ranger")
save(spamRgThres, file = "outputs/spamRgThres.Rdata")
```

```{r}
spamRgThres$comput.time
```

```{r, eval=FALSE}
spamRgThresParaRg <- VSURF_thres(type~., spamApp, parallel = TRUE, ncores = ncores, clusterType = "ranger", RFimplem = "ranger")
save(spamRgThresParaRg, file = "outputs/spamRgThresParaRg.Rdata")
```

```{r}
spamRgThresParaRg$comput.time
```


## Interpretation step

```{r, eval=FALSE}
spamInterp <- VSURF_interp(type~., spamApp, vars = spamThres$varselect.thres, parallel = TRUE, ncores = ncores, clusterType = "FORK")
save(spamInterp, file = "outputs/spamInterp.Rdata")
```

```{r}
spamInterp$comput.time
```

```{r, eval=FALSE}
spamRgInterp <- VSURF_interp(type~., spamApp, vars = spamThres$varselect.thres, parallel = TRUE, ncores = ncores, clusterType = "FORK", RFimplem = "ranger")
save(spamRgInterp, file = "outputs/spamRgInterp.Rdata")
```

```{r}
spamRgInterp$comput.time
```

```{r, eval=FALSE}
spamRgInterpParaRg <- VSURF_interp(type~., spamApp, vars = spamThres$varselect.thres, parallel = TRUE, ncores = ncores, clusterType = "ranger", RFimplem = "ranger")
save(spamRgInterpParaRg, file = "outputs/spamRgInterpParaRg.Rdata")
```

```{r}
spamRgInterpParaRg$comput.time
```

```{r, eval=FALSE}
spamRbInterp <- VSURF_interp(type~., spamApp, vars = spamThres$varselect.thres, parallel = TRUE, ncores = ncores, clusterType = "FORK", RFimplem = "Rborist")
save(spamRbInterp, file = "outputs/spamRbInterp.Rdata")
```

```{r}
spamRbInterp$comput.time
```

```{r, eval=FALSE}
spamRbInterpParaRb <- VSURF_interp(type~., spamApp, vars = spamThres$varselect.thres, parallel = TRUE, ncores = ncores, clusterType = "Rborist", RFimplem = "Rborist")
save(spamRbInterpParaRb, file = "outputs/spamRbInterpParaRb.Rdata")
```

```{r}
spamRbInterpParaRb$comput.time
```

## Prediction step

```{r, eval=FALSE}
spamPred <- VSURF_pred(type~., spamApp, err.interp = spamInterp$err.interp, varselect.interp = spamInterp$varselect.interp, parallel = TRUE, ncores = ncores, clusterType = "FORK")
save(spamPred, file = "outputs/spamPred.Rdata")
```

```{r}
spamPred$comput.time
```

```{r, eval=FALSE}
spamRgPred <- VSURF_pred(type~., spamApp, err.interp = spamInterp$err.interp, varselect.interp = spamInterp$varselect.interp, RFimplem = "ranger")
save(spamRgPred, file = "outputs/spamRgPred.Rdata")
```

```{r}
spamRgPred$comput.time
```

```{r, eval=FALSE}
spamRgPredParaRg <- VSURF_pred(type~., spamApp, err.interp = spamInterp$err.interp, varselect.interp = spamInterp$varselect.interp, RFimplem = "ranger", num.threads = ncores)
save(spamRgPredParaRg, file = "outputs/spamRgPredParaRg.Rdata")
```

```{r}
spamRgPredParaRg$comput.time
```

```{r, eval=FALSE}
spamRbPred <- VSURF_pred(type~., spamApp, err.interp = spamInterp$err.interp, varselect.interp = spamInterp$varselect.interp, RFimplem = "Rborist")
save(spamRbPred, file = "outputs/spamRbPred.Rdata")
```

```{r, eval=FALSE}
spamRbPred$comput.time
```

```{r, eval=FALSE}
spamRbPredParaRb <- VSURF_pred(type~., spamApp, err.interp = spamInterp$err.interp, varselect.interp = spamInterp$varselect.interp, RFimplem = "Rborist", nThread = 5)
save(spamRbPredParaRb, file = "outputs/spamRbPredParaRb.Rdata")
```

```{r, eval=FALSE}
spamRbPredParaRb$comput.time
```

## Parallel with `ranger`

### Fork

```{r, eval=FALSE}
spamRangerFork <- VSURF(type~., spamApp, RFimplementation = "ranger",
                   parallel = TRUE, ncores = ncores,
                   clusterType = "FORK")
```

```{r, eval=FALSE}
summary(spamRangerFork)
```

### Internal

```{r, eval=FALSE}
spamRangerInter <- VSURF(spamApp[, -58], spamApp[, 58],
                         RFimplementation = "ranger", parallel = TRUE,
                         ncores = ncores, clusterType = "ranger")
summary(spamRangerInter)
```


# `vac18` data

```{r introVac18Load, cache=FALSE}
data("vac18", package = "mixOmics")
geneExpr <- vac18$genes
stimu <- vac18$stimulation
ncores <- 3
```

## Parallel with `randomForest`

```{r, eval=FALSE}
vacRF <- VSURF(x = geneExpr, y = stimu, parallel = TRUE, ncores = ncores, clusterType = "FORK")
save(vacRF, file = "outputs/vacRF.Rdata")
```

```{r}
summary(vacRF)
```


## Parallel with `ranger`

### Fork

```{r, eval=FALSE}
vacRgThres <- VSURF_thres(x = geneExpr, y = stimu, parallel = TRUE, ncores = ncores, RFimplem = "ranger", clusterType = "FORK")
save(vacRgThres, file = "outputs/vacRgThres.Rdata")
```

```{r}
vacRgThres$comput.time
```

```{r, eval=FALSE}
vacRgInterp <- VSURF_interp(x = geneExpr, y = stimu, parallel = TRUE, ncores = ncores, RFimplem = "ranger", clusterType = "FORK", vars = vacRF$varselect.thres)
save(vacRgInterp, file = "outputs/vacRgInterp.Rdata")
```

```{r}
vacRgInterp$comput.time
```

```{r, eval=FALSE}
vacRgPred <- VSURF_pred(x = geneExpr, y = stimu, RFimplem = "ranger", varselect.interp = vacRF$varselect.interp, err.interp = vacRF$err.interp)
save(vacRgPred, file = "outputs/vacRgPred.Rdata")
```

```{r}
vacRgPred$comput.time
```
